# -*- coding: utf-8 -*-
"""Actividad2Lezcano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpA7elPMhK5morxnjBIXwN8kbJhRo43f

Bienvenida = ("Hola mundo");
A = 1;
B = 3;
print (Bienvenida, A + B);
"""



class Perro:
    def __init__(self, nombre, raza):
        self.nombre = nombre
        self.raza = raza

    def jugar_con_pelota(self):
        return f"{self.nombre}, el {self.raza}, está jugando con su pelota de tenis."

    def ladrar(self):
        return f"{self.nombre} está ladrando: ¡Guau, guau!"

mi_perro = Perro("Aquiles", "Cocker Spaniel")
resultado = mi_perro.jugar_con_pelota()
print(resultado)

ladrido_aquiles = mi_perro.ladrar()
print(ladrido_aquiles)

class Auto:
  def __init__(self, marca, modelo, color):
    self.marca = marca
    self.modelo = modelo
    self.color = color

  def acelerar(self):
    return f"El {self.marca} modelo {self.modelo} de color {self.color} está acelerando"
  def frenar(self):
    return f"El {self.marca} modelo {self.modelo} de color {self.color} está frenando"

mi_auto = Auto("Peugeot", "207", "Blanco")
acelerando = mi_auto.acelerar()
print(acelerando)
frenando = mi_auto.frenar()
print(frenando)